#' Save hysplit trajectory data to objects containing sample id, sample location,
#' system (ERA5/GDAS) and the trajectory object 

source("src/preprocessing/read_hysplit-traj.R")
source("src/preprocessing/puntos-muestreo-artico.R")
source("src/preprocessing/puntos-muestreo-antartida.R")
rootwd <- getwd()

#' Generate trajectory object list
#' @param localization "GL" or "ANT" for samples taken in Greenland and Antartica resp.
#' @param reanalysis Reanalysis method: "ERA5" or "GDAS"
#' @note
#' TODO: Add ANT cases
#' TODO: Implement error handler for unexpected input and if file list is empty
#' 

generate.traj.obj <- function(localization,reanalysis){
  
  # Get file names according to given parameters
  filename.list <- list()
  data.path <- ""
  if(localization=="GL" && reanalysis=="ERA5"){
    data.path <- "data/groenlandia/raw/EXPTdV-Groenlandia-ERA5/"
    filename.list <- list.files(data.path, pattern = "EXPTdV")
  }
  
  if(localization=="GL" && reanalysis=="GDAS"){
    data.path <- "data/groenlandia/raw/EXPTdV-Groenlandia-GDAS/"
    filename.list <- list.files(data.path, pattern = "EXPTdV")
  }
  
  if(localization=="ANT" && reanalysis=="ERA5"){
    data.path <- "data/antartida/raw/ERA5/"
    filename.list <- list.files(data.path, pattern = "EXP21")
  }
  
  if(localization=="ANT" && reanalysis=="GDAS"){
    data.path <- "data/antartida/raw/GDAS/"
    filename.list <- list.files(data.path, pattern = "EXP21")
  }
  
  # Declare global trajectory list
  btraj.list <- list()
  
  # read.hysplit.traj requires the wd to be the files directory
  setwd(data.path)
  # Define a variable to keep track of progress
  n.iter <- 0
  total.iter <- length(filename.list)
  # Populate list with elements that are lists which contain backwards trajectories
  btraj.list.len <- 0
  for (filename in filename.list){
    # TODO: add more variables to the (lower level) lists: 
    #     sampling id, location, start and end time, number of points in traj
    
    cat(paste("Processing ",localization, " ", reanalysis, " Hysplit trajectories: ", n.iter <- n.iter+1,"/",total.iter,"\r",sep = ""))
    traj.obj.list <- read.hysplit.traj(filename)
    #Unpacking of the list object provided by read.hysplit.traj
    for(traj.obj in traj.obj.list){
      traj.obj$Metadata$Reanalysis <- reanalysis
      
      end.lat = traj.obj$Trajectory$Lat[1]
      end.long = traj.obj$Trajectory$Long[1]
      if(localization == "GL"){
        traj.obj$Metadata$SamplingPoint <- get.punto.muestreo.artico(end.lat,end.long)
        traj.obj$Metadata$SamplingId <- get.muestreo.artico(traj.obj$Metadata$EndDatetime)
      }
      
      if(localization == "ANT"){
        traj.obj$Metadata$SamplingPoint <- get.punto.muestreo.ant(end.lat,end.long)
        traj.obj$Metadata$SamplingId <- get.muestreo.ant(traj.obj$Metadata$EndDatetime)
      }
      
      btraj.list[[btraj.list.len+1]] <- traj.obj
      btraj.list.len <- btraj.list.len + 1
    }
  }
  setwd(rootwd)
  
  btraj.list
}

#' Save trajectory object list generated by generate.traj.obj
#' @param localization "GL" or "ANT" for samples in Greenland and Antartica resp.
#' @param reanalysis Reanalysis method: "ERA5" or "GDAS"
#' @note
#' TODO: Implement error handler for unexpected input and if file list is empty
#' 
save.traj.obj <- function(localization, reanalysis){
  trajectory.obj <- generate.traj.obj(localization, reanalysis)
  
  # Generate file name and path according to given parameters
  save.path <- ""
  if(localization=="GL" && reanalysis=="ERA5"){
    save.path <- "data/groenlandia/processed/unsampled/groenlandia_ERA5_btraj.rds"
  }
  
  if(localization=="GL" && reanalysis=="GDAS"){
    save.path <- "data/groenlandia/processed/unsampled/groenlandia_GDAS_btraj.rds"
  }
  
  if(localization=="ANT" && reanalysis=="ERA5"){
    save.path <- "data/antartida/processed/unsampled/antartida_ERA5_btraj.rds"
  }
  
  if(localization=="ANT" && reanalysis=="GDAS"){
    save.path <- "data/antartida/processed/unsampled/antartida_GDAS_btraj.rds"
  }
  
  
  saveRDS(trajectory.obj,file = save.path)
}


