library(MASS)
source("src/sp2-pointcloud/density-estimation.R")

#' Auxiliary function for getting x and y ranges in the computation of
#' Hellinger distance
get_density_lims <- function(btraj.obj.list) {
  x = c()
  y = c()
  
  for (btraj.obj in btraj.obj.list) {
    n.points <- btraj.obj$Metadata$SampleSize
    x.traj <- btraj.obj$Trajectory$xProj[1:n.points]
    y.traj <- btraj.obj$Trajectory$yProj[1:n.points]
    
    x <- c(x, x.traj)
    y <- c(y, y.traj)
  }
  
  
  range.x <- range(x)
  xl = range.x[1]
  xu = range.x[2]
  x.dif <- xu - xl
  
  range.y <- range(y)
  yl = range.y[1]
  yu = range.y[2]
  y.dif <- yu - yl
  
  #add margins to the bounds
  margin <- 0.1
  xl <- xl - margin * x.dif
  xu <- xu + margin * x.dif
  yl <- yl - margin * y.dif
  yu <- yu + margin * y.dif
  
  c(xl, xu, yl, yu)
}

#'TODO: Implement another auxilary function to select an appropriate bandwidth
# get_bandwidth <- function(btraj.obj.list){
#   sapply(btraj.obj.list, function(obj){obj$Metadata$TrajLength/obj$Metadata$Sample})
# }

#' Compute an approximation of the Hellinger distance between the estimated
#' densities generated by the discretization points of two sets of trajectories

hellinger_dist <-  function(btraj.obj.list.1,
                            btraj.obj.list.2,
                            gridpoints = 25) {
  bol1 <- btraj.obj.list.1
  bol2 <- btraj.obj.list.2
  
  lims <- get_density_lims(c(bol1, bol2))
  
  dist1 <-
    estimate_2d_density_trajs(bol1, n = gridpoints, lims = lims)$z
  dist2 <-
    estimate_2d_density_trajs(bol2, n = gridpoints, lims = lims)$z
  
  xl <- lims[1]
  xu <- lims[2]
  yl <- lims[3]
  yu <- lims[4]

  grid.rectangle.area <- ((xu - xl)/(gridpoints - 1)) * ((yu - yl)/(gridpoints - 1))
  
  sqrt(0.5 * grid.rectangle.area * sum((sqrt(dist1) - sqrt(dist2)) ^ 2))
}
